# apiVersion: v1
# kind: Service
# metadata:
#   name: house-price-prediction
# spec:
#   selector:
#     app: house-price-prediction
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 80
#   type: LoadBalancer

apiVersion: v1
kind: Service
metadata:
  name: house-price-prediction-service
spec:
  selector:
    app: house-price-prediction
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000